import type { GeneratePasswordOptions } from '../core/password';
import type { GeneratePinOptions } from '../core/pin';
import type { SecretFormat } from '../core/types';
import type { SecretPreset, TokenPresetOptions } from './types';

const tokenFormats: SecretFormat[] = ['base64url-no-padding', 'base64', 'hex'];
const wideTokenBits = [128, 192, 256, 384, 512];
const highTokenBits = [256, 384, 512];

const randomPasswordDefaults: GeneratePasswordOptions = {
  length: 32,
  uppercase: true,
  lowercase: true,
  digits: true,
  symbols: true,
  symbolMode: 'safe-symbols',
  excludeAmbiguous: false,
  requireEachSelectedType: true,
};

const signInPasswordDefaults: GeneratePasswordOptions = {
  ...randomPasswordDefaults,
  length: 24,
  symbolMode: 'all-symbols',
};

const databasePasswordDefaults: GeneratePasswordOptions = {
  ...randomPasswordDefaults,
  length: 32,
  symbolMode: 'safe-symbols',
};

const pinDefaults: GeneratePinOptions = {
  length: 6,
  allowLeadingZero: true,
  avoidRepeating: true,
  avoidSequential: true,
};

function tokenDefaults(bits = 256, format: SecretFormat = 'base64url-no-padding'): TokenPresetOptions {
  return { bits, format };
}

export const secretPresets = [
  {
    id: 'random-password',
    category: 'password',
    generator: 'password',
    label: 'Random password',
    description: 'A high-entropy random password made from selected character sets.',
    aliases: ['password', 'custom password', 'random string'],
    defaultOptions: randomPasswordDefaults,
    allowedLengths: [8, 12, 16, 20, 24, 32, 48, 64, 96, 128, 192, 256],
    warnings: [
      'This password is not designed to be memorable. Store it in a password manager or secret manager.',
      'Check the target system password rules before using symbols.',
    ],
    order: 10,
  },
  {
    id: 'sign-in-password',
    category: 'password',
    generator: 'password',
    label: 'Sign-in password',
    description: 'A login password for web services and admin screens.',
    aliases: ['login', 'account', 'admin password', 'service password'],
    defaultOptions: signInPasswordDefaults,
    allowedLengths: [12, 16, 20, 24, 32, 48, 64, 96, 128],
    warnings: [
      'The target service may have its own maximum length and symbol rules.',
      'This tool does not guarantee service-specific compatibility.',
    ],
    order: 20,
  },
  {
    id: 'database-password',
    category: 'password',
    generator: 'password',
    label: 'Database password',
    description: 'A database user password with DSN-friendly safe symbols by default.',
    aliases: ['db', 'postgres', 'mysql', 'redis', 'mongodb', 'dsn'],
    defaultOptions: databasePasswordDefaults,
    allowedLengths: [16, 20, 24, 32, 48, 64, 96, 128],
    warnings: [
      'When embedding in a DSN, URL encoding may still be required.',
      'Safe symbols improve compatibility but reduce the character set size at the same length.',
    ],
    order: 30,
  },
  {
    id: 'pin',
    category: 'numeric-code',
    generator: 'pin',
    label: 'PIN',
    description: 'A numeric code for short-term or temporary use.',
    aliases: ['numeric code', 'digits', 'otp-like', 'device code'],
    defaultOptions: pinDefaults,
    allowedLengths: [4, 6, 8, 12],
    warnings: [
      'PINs are not suitable as long-term secrets.',
      'Use a token or password preset when you need stronger protection.',
    ],
    order: 40,
  },
  {
    id: 'api-token',
    category: 'token',
    generator: 'token',
    label: 'API token',
    description: 'A URL-safe API-key style token, optionally with a prefix.',
    aliases: ['api key', 'bearer token', 'access token', 'sk'],
    defaultOptions: { ...tokenDefaults(), prefix: 'sk_' },
    allowedBits: wideTokenBits,
    allowedFormats: tokenFormats,
    warnings: ['A prefix helps identify the token type, but does not add entropy.'],
    order: 50,
  },
  {
    id: 'webhook-secret',
    category: 'token',
    generator: 'token',
    label: 'Webhook secret',
    description: 'A shared secret for webhook signature verification.',
    aliases: ['webhook', 'signature', 'hmac webhook', 'whsec'],
    defaultOptions: { ...tokenDefaults(), prefix: 'whsec_' },
    allowedBits: highTokenBits,
    allowedFormats: tokenFormats,
    warnings: ['Do not publish webhook secrets in public repositories or logs.'],
    order: 60,
  },
  {
    id: 'session-secret',
    category: 'token',
    generator: 'token',
    label: 'Session secret',
    description: 'A secret for signing cookies or server-side sessions.',
    aliases: ['cookie secret', 'session signing', 'app secret'],
    defaultOptions: tokenDefaults(),
    allowedBits: highTokenBits,
    allowedFormats: tokenFormats,
    warnings: [
      'Changing a session secret may invalidate existing sessions.',
      'Multiple app instances may need to share the same value.',
    ],
    order: 70,
  },
  {
    id: 'csrf-secret',
    category: 'token',
    generator: 'token',
    label: 'CSRF secret',
    description: 'A secret for generating or signing CSRF tokens.',
    aliases: ['csrf', 'anti csrf', 'xsrf'],
    defaultOptions: tokenDefaults(),
    allowedBits: [128, 192, 256],
    allowedFormats: tokenFormats,
    warnings: ['A CSRF token and the secret used to sign tokens may be different values.'],
    order: 80,
  },
  {
    id: 'jwt-hs256',
    category: 'jwt-secret',
    generator: 'token',
    label: 'JWT HS256 secret',
    description: 'A shared HMAC secret for JWT HS256 signing.',
    aliases: ['jwt', 'hs256', 'hmac', 'json web token'],
    defaultOptions: tokenDefaults(256),
    allowedBits: [256, 384, 512],
    allowedFormats: tokenFormats,
    warnings: ['HS algorithms use shared secrets, not public/private key pairs.'],
    order: 90,
  },
  {
    id: 'jwt-hs384',
    category: 'jwt-secret',
    generator: 'token',
    label: 'JWT HS384 secret',
    description: 'A shared HMAC secret for JWT HS384 signing.',
    aliases: ['jwt', 'hs384', 'hmac', 'json web token'],
    defaultOptions: tokenDefaults(384),
    allowedBits: [384, 512],
    allowedFormats: tokenFormats,
    warnings: ['Do not use a value shorter than the intended HS384 strength.'],
    order: 100,
  },
  {
    id: 'jwt-hs512',
    category: 'jwt-secret',
    generator: 'token',
    label: 'JWT HS512 secret',
    description: 'A shared HMAC secret for JWT HS512 signing.',
    aliases: ['jwt', 'hs512', 'hmac', 'json web token'],
    defaultOptions: tokenDefaults(512),
    allowedBits: [512],
    allowedFormats: tokenFormats,
    warnings: ['This is a shared secret and must not be published.'],
    order: 110,
  },
  {
    id: 'aes-gcm-key',
    category: 'encryption-key',
    generator: 'token',
    label: 'AES-GCM key',
    description: 'A raw symmetric key for AES-GCM encryption use cases.',
    aliases: ['aes', 'gcm', 'encryption key', 'symmetric key'],
    defaultOptions: tokenDefaults(256),
    allowedBits: [128, 192, 256],
    allowedFormats: tokenFormats,
    warnings: [
      'An AES-GCM key is not a nonce or IV.',
      'Never reuse the same AES-GCM key and nonce pair.',
    ],
    order: 120,
  },
  {
    id: 'hmac-sha256-key',
    category: 'encryption-key',
    generator: 'token',
    label: 'HMAC-SHA-256 key',
    description: 'A shared key for HMAC-SHA-256 signing or integrity checks.',
    aliases: ['hmac', 'sha256', 'mac', 'signing key'],
    defaultOptions: tokenDefaults(256),
    allowedBits: [256, 384, 512],
    allowedFormats: tokenFormats,
    warnings: ['HMAC keys are shared secrets. Do not expose them in client code.'],
    order: 130,
  },
  {
    id: 'hmac-sha384-key',
    category: 'encryption-key',
    generator: 'token',
    label: 'HMAC-SHA-384 key',
    description: 'A shared key for HMAC-SHA-384 signing or integrity checks.',
    aliases: ['hmac', 'sha384', 'mac', 'signing key'],
    defaultOptions: tokenDefaults(384),
    allowedBits: [384, 512],
    allowedFormats: tokenFormats,
    warnings: ['HMAC keys are shared secrets. Keep them out of logs and repositories.'],
    order: 140,
  },
  {
    id: 'hmac-sha512-key',
    category: 'encryption-key',
    generator: 'token',
    label: 'HMAC-SHA-512 key',
    description: 'A shared key for HMAC-SHA-512 signing or integrity checks.',
    aliases: ['hmac', 'sha512', 'mac', 'signing key'],
    defaultOptions: tokenDefaults(512),
    allowedBits: [512],
    allowedFormats: tokenFormats,
    warnings: ['HMAC keys are shared secrets. Keep them out of logs and repositories.'],
    order: 150,
  },
  {
    id: 'hex-token',
    category: 'random',
    generator: 'token',
    label: 'Hex token',
    description: 'A random token encoded as lowercase hexadecimal.',
    aliases: ['hex', 'random hex', 'token'],
    defaultOptions: tokenDefaults(256, 'hex'),
    allowedBits: wideTokenBits,
    allowedFormats: ['hex'],
    order: 160,
  },
  {
    id: 'base64-token',
    category: 'random',
    generator: 'token',
    label: 'Base64 token',
    description: 'A random token encoded as standard Base64.',
    aliases: ['base64', 'random base64', 'token'],
    defaultOptions: tokenDefaults(256, 'base64'),
    allowedBits: wideTokenBits,
    allowedFormats: ['base64'],
    warnings: ['Standard Base64 may include +, /, and = characters.'],
    order: 170,
  },
  {
    id: 'base64url-token',
    category: 'random',
    generator: 'token',
    label: 'Base64url token',
    description: 'A random token encoded as URL-safe Base64 without padding.',
    aliases: ['base64url', 'url safe token', 'cookie token'],
    defaultOptions: tokenDefaults(),
    allowedBits: wideTokenBits,
    allowedFormats: ['base64url-no-padding', 'base64url'],
    order: 180,
  },
  {
    id: 'random-bytes',
    category: 'random',
    generator: 'token',
    label: 'Random bytes',
    description: 'A raw random byte sequence displayed using an encoding.',
    aliases: ['bytes', 'binary', 'random data'],
    defaultOptions: tokenDefaults(256, 'hex'),
    allowedBits: [128, 192, 256, 384, 512],
    allowedFormats: tokenFormats,
    warnings: ['Raw bytes are encoded for display and copying.'],
    order: 190,
  },
  {
    id: 'uuid-v4',
    category: 'random',
    generator: 'uuid',
    label: 'UUID v4',
    description: 'A random UUID v4 identifier.',
    aliases: ['uuid', 'guid', 'random id', 'identifier'],
    defaultOptions: {},
    warnings: [
      'UUID v4 is primarily an identifier. For strong secrets, use a 256-bit token.',
    ],
    order: 200,
  },
  {
    id: 'env-secret',
    category: 'env',
    generator: 'token',
    label: '.env secret',
    description: 'A KEY=value secret for application environment files.',
    aliases: ['env', 'dotenv', 'app secret', 'nextauth', 'session secret'],
    defaultOptions: { ...tokenDefaults(), envKey: 'APP_SECRET' },
    allowedBits: wideTokenBits,
    allowedFormats: tokenFormats,
    warnings: [
      'Do not commit .env files to public repositories.',
      'Check framework-specific format and length requirements when applicable.',
    ],
    order: 210,
  },
] satisfies SecretPreset[];

export function getPresetById(presetId: string): SecretPreset | undefined {
  return secretPresets.find((preset) => preset.id === presetId);
}

export function getDefaultPreset(): SecretPreset {
  return getPresetById('random-password') ?? secretPresets[0];
}

export const envKeySuggestions = [
  'APP_SECRET',
  'SESSION_SECRET',
  'JWT_SECRET',
  'CSRF_SECRET',
  'WEBHOOK_SECRET',
  'ENCRYPTION_KEY',
] as const;
